export enum Expressions {
  StringLiteral = 'string-expr',
  NullLiteral = 'null-literal',
  NumberLiteral = 'number-expr',
  BooleanLiteral = 'boolean-expr',
  Binary = 'binary-expr',
  BinaryComp = 'binary-comp-expr',
  Variable = 'variable-expr',
  Assign = 'assign-expr',
  Read = 'read-expr',
  Concat = 'concat-expr',
  ToString = 'to-string-expr',
  ToNumber = 'to-number-expr',
  ToBoolean = 'to-boolean-expr',
  Logical = 'logical-expr',
  AssignOp = 'assign-op-expr',
  Increment = 'increment-expr',
}
